---
title: 'Homework 5: Iteration'
author: "Kimberly Lopez"
date: "2024-11-06"
output: github_document
---
```{r}
library(tidyverse)
library(rvest)
library(broom)
library(dplyr)
```

```{r}
set.seed(5)
```

# Problem 1 

# Problem 2

For one randomly generated sample of n=30, with mean = 0, and sd= 5, run a t.test() and return the estimate & p-value: 
```{r}
sim_data = 
    tibble(
    x = rnorm (30, mean= 0, sd= 5))

t.test(sim_data)|>
  broom::tidy()|>
  select(estimate,p.value)
```


Function for performing a one-sample t-test and returning the estimate & p-value
 
```{r}

sim_t_test = function ( n , mu= 0, sigma =5) {
  
  sim_data = 
    tibble(
    x = rnorm (n, mean= mu, sd= sigma))
  
  sim_data|>
    t.test()|>
    broom::tidy()|>
    select(estimate, p.value)
  
}

sim_t_test(n=30)
```
For 5000 datasets: 
```{r}
output = vector("list", 5000)

for (i in 1:5000) {
  output[[i]] = sim_t_test(n=30)
}

sim_results_mu1 = bind_rows(output)

sim_results_mu1
```

```{r}
output = vector("list", 5000)

for (i in 1:5000) {
  output[[i]] = sim_t_test(n=30,mu=2)
}

sim_results_mu2 = bind_rows(output)

sim_results_mu2
```

Function for calculating power: the proportion of times the null was rejected 
```{r}

sim_power = function ( data) {
  
  data|>
   filter(p.value < 0.05) |>
  summarize(
    power = n() / nrow(data))
  
}

sim_power(sim_results_mu2)

```



```{r}
output = vector("list", 5000)

for (i in 1:5000) {
  output[[i]] = sim_t_test(n=30,mu=3)
}

sim_results_mu3 = bind_rows(output)

sim_results_mu3
```

```{r}

```



# Problem 3 


